FROM debian:bullseye-slim

ARG TARGETARCH
ARG TARGETVARIANT

RUN dpkg --add-architecture $TARGETARCH$TARGETVARIANT && \
    apt update && apt upgrade -y

ARG STARTAPP

WORKDIR /app
COPY $TARGETARCH$TARGETVARIANT.deb/* .

RUN apt install ./$STARTAPP-$TARGETARCH$TARGETVARIANT.deb -y

VOLUME /vids

CMD ["$STARTAPP"]