name: Compile and Package
on:
  push:
    branches: [ main ]

  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  compile:
    runs-on: ubuntu-20.04
    permissions:
      packages: write

    strategy:
      matrix:
        include:
          - arch: aarch64
            distro: bullseye
          - arch: armv7
            distro: bullseye
          - arch: amd64

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: arm builds
        if: matrix.arch != 'amd64'
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
          # github.token doesn't grant access into packages
          # githubToken: ${{ secrets.PUSH_PACKAGE }}
          githubToken: ${{ github.token }}
          install: |
            apt update && apt upgrade -y
            apt install -y libboost-all-dev
            apt install -y gstreamer1.0-plugins-base \
              gstreamer1.0-plugins-good gstreamer1.0-plugins-bad \
              gstreamer1.0-plugins-ugly gstreamer1.0-libav \
              gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa \
              gstreamer1.0-gl  
            apt install -y libpango1.0-dev
            apt install -y libavfilter-dev
            apt install -y libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
              libgstreamer-plugins-bad1.0-dev 
            apt install -y libgstrtspserver-1.0-dev
            apt install -y libmariadb-dev libgps-dev
            apt install -y build-essential
            apt install -y cmake fakeroot

          run: |
              make github ARCH=${{ matrix.arch }}

      - name: amd build
        if: matrix.arch == 'amd64'
        run: |
          sudo apt update && sudo apt upgrade -y
          sudo apt install -y libboost-all-dev
          sudo apt install -y gstreamer1.0-plugins-base \
            gstreamer1.0-plugins-good gstreamer1.0-plugins-bad \
            gstreamer1.0-plugins-ugly gstreamer1.0-libav \
            gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa \
            gstreamer1.0-gl  
          sudo apt install -y libpango1.0-dev
          sudo apt install -y libavfilter-dev
          sudo apt install -y libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
            libgstreamer-plugins-bad1.0-dev 
          sudo apt install -y libgstrtspserver-1.0-dev
          sudo apt install -y libmariadb-dev
          sudo apt install -y build-essential
          sudo apt install -y cmake fakeroot

          make github ARCH=${{ matrix.arch }}
   
        shell: bash

      - name: artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.arch }}.deb
          path: |
            ./*${{ matrix.arch }}.deb

  docker:
    runs-on: ubuntu-20.04
    needs: compile
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: fetch
        uses: actions/download-artifact@v3
        with:
          path: ./

      - name: get-buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: build the image
        run: |
          docker buildx build \
            --tag barneyman/ringbuffer:latest \
            --platform linux/amd64,linux/arm/v7,linux/arm64 \
            --build-arg STARTAPP=ringbuffer
            -f buildx/Dockerfile.ringbuffer .
        shell: bash



      # - name: gstreamer
      #   run: |
      #     sudo apt install -y gstreamer1.0-plugins-base \
      #       gstreamer1.0-plugins-good gstreamer1.0-plugins-bad \
      #       gstreamer1.0-plugins-ugly gstreamer1.0-libav \
      #       gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa \
      #       gstreamer1.0-gl  

      # - name: gstreamer-dev
      #   run: |
      #     sudo apt install -y libpango1.0-dev
      #     sudo apt install -y libavfilter-dev
      #     sudo apt install -y libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
      #       libgstreamer-plugins-bad1.0-dev 
      #     sudo apt install -y libgstrtspserver-1.0-dev

      # - name: sql-dev
      #   run: |
      #       sudo apt install -y libmariadb-dev

      # - name: compile
      #   run: make

      # - name: package
      #   uses: kentik/pkg@1.0.0-rc8
      #   with:
      #     name: dashcam-server
      #     version: 0.0.1
      #     arch: x86_64
      #     format: deb
      #     package: package.yaml
