name: Compile and Package
on:
  push:
    branches: [ main ]

  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  compile:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - arch: aarch64
            distro: bullseye
          - arch: armv7
            distro: bullseye

    steps:
      - name: checkout
        uses: actions/checkout@v2.7.0
        with:
          submodules: 'recursive'

      - name: tools
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
          # github.token doesn't grant access into packages
          githubToken: ${{ secrets.PUSH_PACKAGE }}
          install: |
            apt update && apt upgrade -y
            apt install -y libboost-all-dev
            apt install -y gstreamer1.0-plugins-base \
              gstreamer1.0-plugins-good gstreamer1.0-plugins-bad \
              gstreamer1.0-plugins-ugly gstreamer1.0-libav \
              gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa \
              gstreamer1.0-gl  
            apt install -y libpango1.0-dev
            apt install -y libavfilter-dev
            apt install -y libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
              libgstreamer-plugins-bad1.0-dev 
            apt install -y libgstrtspserver-1.0-dev
            apt install -y libmariadb-dev
            apt install -y build-essential
            apt install -y cmake

          run: |
              make github ARCH=${{ matrix.arch }}
      - name: zip
        run: |
          run: tar -czvf ${{ matrix.arch }}.tar.gz *-${{ matrix.arch }}
      - name: artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.arch }}
          path: ${{ matrix.arch }}.tar.gz
         

      # - name: gstreamer
      #   run: |
      #     sudo apt install -y gstreamer1.0-plugins-base \
      #       gstreamer1.0-plugins-good gstreamer1.0-plugins-bad \
      #       gstreamer1.0-plugins-ugly gstreamer1.0-libav \
      #       gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa \
      #       gstreamer1.0-gl  

      # - name: gstreamer-dev
      #   run: |
      #     sudo apt install -y libpango1.0-dev
      #     sudo apt install -y libavfilter-dev
      #     sudo apt install -y libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
      #       libgstreamer-plugins-bad1.0-dev 
      #     sudo apt install -y libgstrtspserver-1.0-dev

      # - name: sql-dev
      #   run: |
      #       sudo apt install -y libmariadb-dev

      # - name: compile
      #   run: make

      # - name: package
      #   uses: kentik/pkg@1.0.0-rc8
      #   with:
      #     name: dashcam-server
      #     version: 0.0.1
      #     arch: x86_64
      #     format: deb
      #     package: package.yaml