name: Compile and Package
on:
  push:
    branches: [ main ]

  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2.7.0
        with:
          submodules: 'recursive'

      - name: tools
        run: |
          apt install -y libboost-all-dev

      - name: gstreamer
        run: |
          apt install -y gstreamer1.0-plugins-base \
            gstreamer1.0-plugins-good gstreamer1.0-plugins-bad \
            gstreamer1.0-plugins-ugly gstreamer1.0-libav \
            gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa \
            gstreamer1.0-gl  

      - name: gstreamer-dev
        run: |
          apt install -y libpango1.0-dev
          apt install -y libavfilter-dev
          apt install -y libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
            libgstreamer-plugins-bad1.0-dev 
          apt install -y libgstrtspserver-1.0-dev

      - name: sql-dev
        run: |
            apt install -y libmariadb-dev

      - name: compile
        run: make

      # - name: package
      #   uses: kentik/pkg@1.0.0-rc8
      #   with:
      #     name: dashcam-server
      #     version: 0.0.1
      #     arch: x86_64
      #     format: deb
      #     package: package.yaml